### ISSUE TITLE
Unable to create Student Group

### ISSUE THREAD

**Issue by chandrubiradar** [frappe/education#107]
I am unable to get students, to the Student group.
I have students, who has enrolled with the same course also has few students who are on same batch. Although i am unable to create student group with students.

Even when I am trying to add students manually, I am getting error. Attaching screenshot

Please look at this issue.
![Screenshot (839)](https://user-images.githubusercontent.com/47516435/218732747-3c6111d2-57b9-49c8-b051-0f24c9244bbc.png)
![Screenshot (837)](https://user-images.githubusercontent.com/47516435/218732754-99462ed2-298e-406e-9ebe-f8db41001cb0.png)
![Screenshot (838)](https://user-images.githubusercontent.com/47516435/218732759-0c5aa042-7d48-489a-a040-a6f8761a2996.png)

Please refer to the Attachments.

**Comment by chandrubiradar** [comment]
@pateljannat Can you please check this issue

**Comment by pateljannat** [comment]
@chandrubiradar can you please add the error you got in console when this issue happened

**Comment by chandrubiradar** [comment]
sharing you in a minute

**Comment by chandrubiradar** [comment]
![Screenshot (846)](https://user-images.githubusercontent.com/47516435/219582212-a6b6e6d6-7372-458f-9b32-731c5cc82e74.png)
![Screenshot (848)](https://user-images.githubusercontent.com/47516435/219582233-4caa537d-7f53-4019-90f5-f19394501a86.png)

Screenshot (846), this error is when I click on Get Students button.
Screenshot (846), this error when i am adding student.

**Comment by chandrubiradar** [comment]
@pateljannat Let me know if you need any details from my end

**Comment by pateljannat** [comment]
@chandrubiradar have you properly updated and migrated your site?

**Comment by chandrubiradar** [comment]
Yes @pateljannat .

Inside Education application. I have run following commands
git pull
bench build education

I believe both the commands should be enough to update an education app

**Comment by chandrubiradar** [comment]
I have updated the app to the recent version ,the issue still occurs. I was unable to figure out what was the issue.


I have fixed the issue by reinstalling the education app.

Thanks @pateljannat for your valuable time.
I really appreciate it.
