### ISSUE TITLE
Cannot Add New Assessment Group

### ISSUE THREAD

**Issue by EkasaTech** [frappe/education#108]
I updated my Education module to "Merge pull Request #105 from vr-greycube/patch-2"
But I still cannot add new Assessment Group. I thought it is fixed on #91 ?
![image](https://user-images.githubusercontent.com/111553452/219325976-7570ef4b-6f2f-4834-b1b6-5ae186901adb.png)

**Comment by pateljannat** [comment]
@EkasaTech what values do you see in the Parent Assessment Group field?

**Comment by EkasaTech** [comment]
Nothing.
Just "Create a new Assesment Group" and "Advanced Search"

I try to connect to database and see nothing inside "tabAssesmentGroup".
no data at all.

Should I uninstall and reinstall my module?


if i uninstall, will my data deleted?

**Comment by pateljannat** [comment]
Don't uninstall. Just make sure your site is properly updated.

**Comment by EkasaTech** [comment]
In case i missed something, can you tell me the step to update my site?
i did "bench update" and "git pull" inside education app

I check education/install.py -> i see your changes to create All Assessment Groups , IgnoreMandatory = true.
Meaning to say that my site should be updated right?

**Comment by EkasaTech** [comment]
> Don't uninstall. Just make sure your site is properly updated.

@pateljannat hi, any update about this? what i should do?

**Comment by pateljannat** [comment]
@EkasaTech can you log in as Administrator and check the Patch Log doctype? In this, do you see an entry for a patch education.patches.v14_0.create_parent_assessment_group #01-01-2022.

**Comment by EkasaTech** [comment]
@pateljannat hi, i cannot see it.

Here my patch log:
![image](https://user-images.githubusercontent.com/111553452/221075049-bf331dd7-e10a-482b-ac95-e5d0e3b81ce7.png)

**Comment by EkasaTech** [comment]
Which one the correct way to update my module?
"bench build" or doing "git pull" manually inside of /frappe-bench/education directory?

**Comment by pateljannat** [comment]
So you should execute the commands in this order

```
bench update

bench --site <sitename> migrate

bench build
```


> hi, i cannot see it.

You should search for create_parent_assessment_group

**Comment by EkasaTech** [comment]
hi @pateljannat , seems it is working now. thanks.
