### ISSUE TITLE
Unknown column 'tabProgram.None' in 'field list'

### ISSUE THREAD

**Issue by tr-j** [frappe/education#112]
In the education module there are several errors on the Fees and Fee Structure pages when querying the Program DocType.

### App Versions
```
{
	"education": "0.0.1",
	"erpnext": "14.17.1",
	"frappe": "14.26.1",
	"hrms": "14.0.3",
	"non_profit": "0.0.1",
	"payments": "0.0.1"
}
```
### Route
```
Form/Program Enrollment/new-program-enrollment-1
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/search.py", line 35, in search_link
    search_widget(
  File "apps/frappe/frappe/desk/search.py", line 194, in search_widget
    values = frappe.get_list(
  File "apps/frappe/frappe/__init__.py", line 1896, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 188, in execute
    result = self.build_and_run()
  File "apps/frappe/frappe/model/db_query.py", line 228, in build_and_run
    return frappe.db.sql(
  File "apps/frappe/frappe/database/database.py", line 219, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'tabProgram.None' in 'field list'")

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"txt": "",
		"doctype": "Program",
		"ignore_user_permissions": 0,
		"reference_doctype": "Program Enrollment"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.search.search_link"
}
```
### Response Data
```
{
	"exception": "pymysql.err.OperationalError: (1054, \"Unknown column 'tabProgram.None' in 'field list'\")"
}
```

### Also:

bench execute --kwargs "{'txt': 'A', 'doctype': 'Program'}" frappe.desk.search.search_link

That produces the same TabProgram.None error.

The SQL query generated is:

select `tabProgram`.`name`, `tabProgram`.None as `label`, `tabProgram`.`program_name`, locate('A', `tabProgram`.`name`) as `_relevance`
		                from `tabProgram`
		                where (`tabProgram`.`name` like '%%A%%' or `tabProgram`.`program_name` like '%%A%%' or `tabProgram`.`name` like '%%A%%')

		                 order by _relevance, `tabProgram`.`modified` DESC, `tabProgram`.idx desc
		                limit 20 offset 0

### Resolution?
It appears that the Program doctype requires a title_field to be set for the queries to work properly.  I think the resolution may be in adding to program/program.json with a default value:
"title_field": "program_name"

Alternatively, the Program List can be customized:
View Settings - Title Field: program_name

This seems to resolve all the errors I've been having, but is this expected behavior?

**Comment by pateljannat** [comment]
@tr-j what are the exact steps you followed on the desk when this error occurred?

**Comment by tr-j** [comment]
We get this error any time the program field is queried for an autocomplete box. Primarily, the fees list page and program enrollment pages.

I'm not sure if there were steps before to create this problem, but I've reset the models and permissions to defaults and was still getting the error.

**Comment by pateljannat** [comment]
@tr-j is your site up to date with the latest version of the education app? Also can you share some screenshots and recordings of when the error occurs

**Comment by tr-j** [comment]
![Screenshot from 2023-03-04 10-50-59](https://user-images.githubusercontent.com/86823725/222875487-0ff94a79-792b-4fa6-abf4-20659f548333.png)

![Screenshot from 2023-03-04 10-51-31](https://user-images.githubusercontent.com/86823725/222875498-5a5ca60a-c9a6-48e6-9bb2-573d7c0402d9.png)

![Screenshot from 2023-03-04 10-51-58](https://user-images.githubusercontent.com/86823725/222875501-aac97b0b-9a56-4afe-8abe-70ee335e8697.png)

**Comment by tr-j** [comment]
I believe it all should be fully upgraded. Education is showing this as the last commit in the app list: [a3510b9](https://github.com/frappe/education/commit/a3510b98218ad2e88b28db0749742b6ec676cb09)

**Comment by RitvikSardana** [comment]
@tr-j 
are you still facing any issues regarding it?

**Comment by RitvikSardana** [comment]
Unable to Replicate this on V15.

@tr-j

**Comment by RitvikSardana** [comment]
Closing the issue due to inactivity, and also that this error is not there anymore.

If you still face the error, re-open this issue @tr-j
