### ISSUE TITLE
is possible to add feature were allow payment have Payment Terms Template or allow it become sales order instead

### ISSUE THREAD

**Issue by johnneijzen** [frappe/education#114]
i want that student are able to payment in installment or at least down payment instead of full price

i taught maybe i can make fee into sales order instead and make student the customer in way it work or maybe there is way to make fee as sales order then allow payment to make in 25% cuts in way instead of full amount

**Comment by RitvikSardana** [comment]
<img width="701" alt="Screenshot 2023-11-03 at 12 34 22 PM" src="https://github.com/frappe/education/assets/65544983/2198961e-9867-4cd4-b7cb-ac33efd8af3f">


Do you want something like this @johnneijzen  ?

**Comment by johnneijzen** [comment]
yes something like that  @RitvikSardana

**Comment by RitvikSardana** [comment]
Fixed Via : https://github.com/frappe/education/pull/181
@johnneijzen
