### ISSUE TITLE
UnboundLocalError when clicking "Get Outstanding Invoice" button in Payment Entry

### ISSUE THREAD

**Issue by osama1998H** [frappe/education#118]
### Description
When I click on the "Get Outstanding Invoice" button in the Payment Entry form, I get an UnboundLocalError with the following message:

`UnboundLocalError: local variable 'voucher_type' referenced before assignment`

This error prevents me from retrieving outstanding invoices for payment.

### Steps to reproduce

1. Log in to the ERPNext instance.
2. Go to the Payment Entry form.
3. Click on the "Get Outstanding Invoice" button.

### Expected behavior
I expect the outstanding invoices to be displayed so that I can select the ones to pay.

### Actual behavior
I get an UnboundLocalError with the message "local variable 'voucher_type' referenced before assignment".

### Environment
Frappe Chat: v0.0.1 (HEAD)
Education: v0.0.1 (HEAD)
ERPNext: v14.17.0 (HEAD)
Erpnext Telegram Integration: v1.2.0 (HEAD)
Frappe Framework: v14.26.0 (HEAD)
Frappe HR: v14.0.3 (HEAD)
Payments: v0.0.1 (HEAD)

**Reproducibility**
Always

### Additional information
I've checked the code, and it seems that the voucher_type variable is not properly assigned before it is referenced. This causes the UnboundLocalError. Can you please investigate this issue and provide a fix? Thank you!

**Comment by RitvikSardana** [comment]
This Issue is fixed,
Closing the issue, re-open if necessary
