### ISSUE TITLE
Student Attendance Tool - Page Not Refeshing\Clearing previous Entries

### ISSUE THREAD

**Issue by tjomtek** [frappe/education#122]
The student attendance tool does not refresh the page on new entry.System setup on "Based on Student Group" Group Based on "batch".
**Replicate this issue** : Select student attendance tool to mark the register , select the "student group" "academic year" and "date". The system will then populate all students linked to that group. Mark the register as normal and click on "mark attendance". At this point the system works initially however select the same group and year but for a **new date** , the system then pulls students linked to that group as normal but shows the previously captured entry , the "user" has to "uncheck all" then mark the register for the new date.
I have tried reloading the page and clearing the caches in the back end , same result.

Tested on version :
ERPNext: v13.49.10 (version-13)
Frappe Framework: v13.52.0 (version-13)
AND 
ERPNext: v13.47.0 (version-13)
Frappe Framework: v13.49.3 (version-13)

**Comment by msalim79** [comment]
any solution/s to this issue , the issue was not present in other versions before the update.

**Comment by RitvikSardana** [comment]
@tjomtek 
Hey, I am not able to replicate this, as this is working at my end, can you explain more?

also I am using v15 and v13 support will end at the end of Dec 2023

**Comment by msalim79** [comment]
The issue is in v13.49 and ERPNext: v13.54.6 (version-13)

Frappe Framework: v13.58.15 (version-13).
Please see attached video. 

Your time to look into this issue is really appreciated :)

https://github.com/frappe/education/assets/30749464/1f9e2a17-8d35-4c2a-8930-dac51eb82a22

**Comment by RitvikSardana** [comment]
This is not replicable in version 15.

@msalim79 @tjomtek

**Comment by msalim79** [comment]
Okay will compare code between versions and fix on my end , since v13 end of support is coming to an end Dec2023, this issue only arose after the upgrade to -
ERPNext: v13.49.10 (version-13)
Frappe Framework: v13.52.0 (version-13)

You can close , thanks for checking and feedback , appreciated.
