### ISSUE TITLE
Does not work with v14 out-of-box

### ISSUE THREAD

**Issue by asifmohtesham** [frappe/education#126]
Fresh installation of ERPNext with Education app is not working with version 14, getting hit by "Internal server error".

**Comment by lawalkeyd** [comment]
Could you expand further on this? I've no issues so far and I'm using version 14

**Comment by asifmohtesham** [comment]
> Could you expand further on this? I've no issues so far and I'm using version 14

At the time of the post (3 weeks ago), with `ERPNext v14.22.2` and `Education` (since there is no release branch so `develop` - 😞), just running ERP out of the box and then following Education steps to get the app installed on the site results in `Internal Server Error` for me.

**Comment by RitvikSardana** [comment]
Hey, are you still facing the issue?

**Comment by RitvikSardana** [comment]
Closing it due to inactivity,
reopen if you still face the same issue
