### ISSUE TITLE
How to print several badges per page to save paper?

### ISSUE THREAD

**Issue by totalys** [frappe/education#133]
I have a custom print setup for student doc_type that prints a badge (photo, qr-code and some info). But we could print up to 6 badges per A4 page to save space.
But print button is only available for one doc at a time.

Is there a way to setup ErpNext to print several doc_types at once so we could print more then one badge per page?

**Comment by hindichurch** [comment]
Adobe PDF Reader can handle this well--printing multiple pages per sheet (as ERPNext mostly generates PDF reports by default).

I know this answer doesn't address native printing in ERPNext, but maybe this workaround can help in the meantime?

**Comment by totalys** [comment]
thanks @hindichurch, but my need is to be able to send more then one badge at a time. Once I can send 4 or 6 students to be printed, I guess it would be simple to configure adobe or other print driver to carry on...

**Comment by RitvikSardana** [comment]
seems like an irrelevant issue, shall I close this?

**Comment by totalys** [comment]
Hi, I'd like to let the community know that I solved this issue this way: 
I've created a doc_type containing a list of the doc_types  I'd like to print (like student_group).
Them, I created a custom print format and I used a for loop to iterate the students from the table inside the document.
<html>
...
{% for student in doc.Students %}
...<htmls>...
{% endfor %}
