### ISSUE TITLE
How to pass a Fees Exemption with refund entry

### ISSUE THREAD

**Issue by reeta-greycube** [frappe/education#14]
Fee exemption:-the government issues some fee concession to students of school that is called Fees-Exemption.

Two option to do fee-Exemption in ERPNext

First Option:-
Fees is created for a student:-
![image](https://user-images.githubusercontent.com/110815754/187836649-69cc6831-cb6d-49f4-8922-b6e2cc04cdca.png)
Payment is received regarding the fees:-
![image](https://user-images.githubusercontent.com/110815754/187836835-496ed137-6355-4e6b-9d00-a4ce4357bd07.png)
A fee exemption journal entry is created:-
![image](https://user-images.githubusercontent.com/110815754/187839601-e1229060-bea7-462c-a712-d34f149985bc.png)
A Refund Journal entry is also created
![image](https://user-images.githubusercontent.com/110815754/187839749-3837a793-9163-4522-9c8b-86230a5b33cd.png)

Second option:-
Fees is created for a student:-
![image](https://user-images.githubusercontent.com/110815754/187844067-9ecbda09-7609-48b3-9bb2-b93e96ff9ac1.png)
Payment is received regarding the fees:-
![image](https://user-images.githubusercontent.com/110815754/187844209-3f466954-b7af-4458-9293-4c57b3ffcab2.png)
A negative fee exemption is created for student:-
![image](https://user-images.githubusercontent.com/110815754/187844625-de046a1e-3391-4b23-99a9-78dd78fee759.png)
A Journal entry for refund is also created:-
![image](https://user-images.githubusercontent.com/110815754/187845137-1844be76-7c99-4d8e-8164-2e0b045f77c5.png)

Which option would be better for doing fees-Exemption from these two?????

**Comment by RitvikSardana** [comment]
So basically you want to give student a discount?
Is this what you want? @reeta-greycube

**Comment by RitvikSardana** [comment]
@reeta-greycube 
fixed via :https://github.com/frappe/education/pull/181
