### ISSUE TITLE
Credit Note Journal Does not Update Fees "outstanding amount"

### ISSUE THREAD

**Issue by msalim79** [frappe/education#141]
Submitted a credit note against a student via a JV , Credit Student Account  and Debit Sales does not update fees doctype "outstanding amount".
The wierd part is that I tried in three different versions of erpnext v13.54.6 (version-13),  v13.49.10 (version-13) and  v13.47.0 (version-13). In v13.47 it works as expected but in the updated versions i.e .49.10 and .54.6 the "outstanding amount" does not get updated.

**Comment by RitvikSardana** [comment]
Have you tried this in the latest version i.e. v15?

**Comment by RitvikSardana** [comment]
As discussed, this is an irrelevant issue hence closing it.
