### ISSUE TITLE
Enhancement on ledgers : future request

### ISSUE THREAD

**Issue by msalim79** [frappe/education#142]
To show actual payment less write off\deductions on seperate lines on the student ledgers.

Current Ledgers 
![image](https://github.com/frappe/education/assets/30749464/bad1925c-28c8-48d8-8861-daa6a826fc77)

Would like to see 

![image](https://github.com/frappe/education/assets/30749464/b7a1b4d0-33f5-4674-9641-64843a7e2486)

**Comment by msalim79** [comment]
Expanding on this request ;
Currently the system by default , does not show "entry type" against a journal in the ledgers , this column has be to added and saved as a seperate report. However when printing the saved ledger the system does not show "entry type" , one would still need to "pick columns" to show "entry type" in the report. This is cumbersome and not practical in the real world where you have hundreds of students.
![EntryTypeOnLedgerBydefault](https://github.com/frappe/education/assets/30749464/c2080112-e9a8-4dea-9326-c7bc4c987c7d)

**Comment by RitvikSardana** [comment]
Fixed via :https://github.com/frappe/education/pull/181
