### ISSUE TITLE
Process Statement Of Accounts for Education - Students(FutureRequest)

### ISSUE THREAD

**Issue by msalim79** [frappe/education#143]
Currently ERPNext has a cool feature "process statement of accounts" , this looks only at the customer table and ledgers.
Could this be replicated to show the Student table with ledgers, specifically for education module.

![image](https://github.com/frappe/education/assets/30749464/35849a99-9b81-4b36-8e93-38738941acb3)

**Comment by RitvikSardana** [comment]
same feature request has already been created 
#113 
Hence closing this
