### ISSUE TITLE
Student Default Email Does Not Populate Automatically when sending email.

### ISSUE THREAD

**Issue by msalim79** [frappe/education#148]
When emailing from fees doctype or any other doctype user has to search for or select the email address, the student email does not populate automatically. Not sure where in the setup this is set ... this school uses gmail as a default.
I have setup other companies not using education module and the system works as expected i.e customers etc

ERPNext: v13.49.10 (version-13)

Frappe Framework: v13.52.0 (version-13)

![DefaultStudentEmail](https://github.com/frappe/education/assets/30749464/33c08ba1-22ec-415a-865c-b9380fb37b7d)

![SelectEmailAddress](https://github.com/frappe/education/assets/30749464/5d8fc518-8afb-43d3-8394-65c0cfa91473)

**Comment by RitvikSardana** [comment]
in version 15, you can select the email of the student from the drop down like this
<img width="775" alt="Screenshot 2023-11-09 at 2 01 59 PM" src="https://github.com/frappe/education/assets/65544983/a5e89161-dbae-4d59-80e0-9ac90a75d180">


I would suggest you to start using v15 of erpnext and frappe and let me know what issues you are facing.

**Comment by msalim79** [comment]
We have that in v13 , if i have 200 students how do you propose i remember that specific students email address?
If you look at the system without education and a contact is added when sending an email the default email address popluates no need to select or search.
![SelectEmailAddress1](https://github.com/frappe/education/assets/30749464/6818db3d-9e66-4d19-901d-8998c7f3f31b)
 
Have a look at  sales invoices , if the customer has a default contact the system fetches the default , see screen shot ...

![SalesInvoiceEG](https://github.com/frappe/education/assets/30749464/9f8152b7-c843-48df-acf2-08ceafcb6ce3)

**Comment by RitvikSardana** [comment]
Yeah, it makes sense, will fix it

**Comment by RitvikSardana** [comment]
<img width="943" alt="Screenshot 2023-11-13 at 11 23 57 PM" src="https://github.com/frappe/education/assets/65544983/cf2d9886-1be7-40e0-be79-e7517d545a01">


I investigated it, and the reason is because when the Email Modal is popped up the modal looks for one of these fields in the doctype, if it is not there then it does not populate the email.
And in "Fees" doctype email is called "student_email".

Will fix it
