### ISSUE TITLE
[Proposal]: In Fees DocType change "student_email" fieldname to "contact_email"

### ISSUE THREAD

**Issue by RitvikSardana** [frappe/education#159]
**Reason**

If we want to send an email from "Fees"  Doctype, when we open the Email modal the email of the student is not auto populated.
![image](https://github.com/frappe/education/assets/65544983/e9ee506e-73d8-4a63-b7d3-f2c39c5dbf8c)

This happens because the Email Modal looks for email/ email_id/ contact_email fieldname in the doctype, if it is not there then it does not populate the email.

Hence, If we will replace the "student_email" fieldname to "contact_email" in the "Fees" Doctype

For More reference look at this issue
https://github.com/frappe/education/issues/148

Reply to this issue, if it could affect your customization

**Comment by msalim79** [comment]
Makes sense to have it create as a "contact" in the system ...
Community members can coment if this would affect their customizations negativaley in any way.
Thanks @RitvikSardana
