### ISSUE TITLE
[Proposal]: Remove Guardian & Sibling Table from Student Applicant WebForm

### ISSUE THREAD

**Issue by RitvikSardana** [frappe/education#160]
![5](https://github.com/frappe/education/assets/65544983/16cf6e49-c4ad-4559-85ee-aa2b0037a260)

"guardian" and "sibling" are link fields and the student filling the form can't create either of these while submitting the form, so it does not make any sense to keep these tables.

Do Reply to this issue, if it could affect your customization

**Comment by msalim79** [comment]
It depends on the case screnario ;
If its a colleage or higher education and they using the student portal I agree but the web form edited to not show these fields.
else if its your primary or high school , silblings and guardians should remain.
Once again if the application is being completed on the portal then those fields could be excluded from the form.
Also we need to take into account who is responsable for paying the account if its not the actual student and if its the "guardain" where would these details be captured.

**Comment by RitvikSardana** [comment]
I am only talking about the WebForm, not anywhere else.

In any situation, the user filling the form can't create a new "sibling" or "guardian" and they will be displayed with all the existing "siblings"/ "Guardians" so I think it makes sense to remove these tables from only the  "WebForm".

**Comment by msalim79** [comment]
makes sense ... I dont see the "Guardians" on the web form by default , no customizations done.

**Comment by RitvikSardana** [comment]
Yeah I just saw, it was added automatically, in version 13 there is no such table "Guardians", in version15 it was added.
