### ISSUE TITLE
Student Fee Collection Report shows wrong Data/Outstanding Amounts

### ISSUE THREAD

**Issue by nitin-anantpranali** [frappe/education#168]
Student Fee Collection Report shows wrong Data/Outstanding Amounts

**Comment by RitvikSardana** [comment]
Showing correct data in Version 15

**Comment by nitin-anantpranali** [comment]
If we pass Payment (Receipt) entry directly then the Outstanding Reports show wrong data.
We have to go via "Fees" screen.
