### ISSUE TITLE
Program wise Fee Collection Report shows wrong Data/Outstanding Amounts

### ISSUE THREAD

**Issue by nitin-anantpranali** [frappe/education#169]
Program wise Fee Collection Report shows wrong Data/Outstanding Amounts

**Comment by RitvikSardana** [comment]
Showing the correct data in Version 15

**Comment by nitin-anantpranali** [comment]
If we pass Payment (Receipt) entry directly then the Outstanding Reports show wrong data.
We have to go via "Fees" screen.

**Comment by RitvikSardana** [comment]
Report showing correct data even if we go directly to Payment Entry in Version 15
