### ISSUE TITLE
There is no connection tab in Fees showing the Payment Entries

### ISSUE THREAD

**Issue by nitin-anantpranali** [frappe/education#170]
There is no connection tab in Fees showing the Payment Entries

**Comment by RitvikSardana** [comment]
Yes there is no connection tab, can add it
<img width="1325" alt="Screenshot 2023-12-05 at 11 51 45 AM" src="https://github.com/frappe/education/assets/65544983/c42e1a98-55c4-4128-95be-a45a7532b948">

But you can view Payment Entries from here

**Comment by nitin-anantpranali** [comment]
A connection tab would help to find all relevant DocTypes.

**Comment by RitvikSardana** [comment]
What connections would you want in Fees Doctype other than Payment Entry

**Comment by RitvikSardana** [comment]
Fixed with sales Invoice
