### ISSUE TITLE
Filtration of student groups programme enrolment

### ISSUE THREAD

**Issue by nitin-anantpranali** [frappe/education#175]
In the program enrolment screen, there should be filtration of the student groups based on the programme selected.
Right now it is showing all the student groups irrespective of the programs selected.

<img width="1265" alt="image" src="https://github.com/frappe/education/assets/116695322/f99d0609-f595-4199-b760-adb5541ec77b">

**Comment by RitvikSardana** [comment]
Which version are you using @nitin-anantpranali ?

**Comment by RitvikSardana** [comment]
Student Group Field in Prog Enrollment is no more in version-15
