### ISSUE TITLE
Filtration of the fee structure in program enrolment.

### ISSUE THREAD

**Issue by nitin-anantpranali** [frappe/education#176]
Programme enrolment screen on fees tab, when we add new fee, system shows all the fee structures available. Instead it should show only relevant fee structure applicable for the selected program.

<img width="1265" alt="image" src="https://github.com/frappe/education/assets/116695322/830df56f-9d98-408d-8f35-c58bf275b325">

**Comment by RitvikSardana** [comment]
Filters are already there in Version 15.
<img width="1294" alt="Screenshot 2023-12-05 at 11 42 06 AM" src="https://github.com/frappe/education/assets/65544983/f5cb47e8-d9f1-4b2d-8f27-4e10efeb71d0">
