### ISSUE TITLE
ModuleNotFoundError: No module named 'education.setup'

### ISSUE THREAD

**Issue by kodeli-lab** [frappe/education#2]
Hi, 
I have installed erpnext education module on erpnext v13, but it does not show in the workspace menu. hence i tried adding it in the domain setting, but i keep getting the above error.  

mean while erpnext run fine.

details:
ubuntu server: 20.04.1
erpnext v13

**Comment by deepeshgarg007** [comment]
Fixed via https://github.com/frappe/education/pull/3
