### ISSUE TITLE
Problem with Program Enrollment cancellation

### ISSUE THREAD

**Issue by nitin-anantpranali** [frappe/education#201]
If I cancel the Program Enrollment, the related Course Enrollment is not getting deleted. As a result I cant delete the Program Enrollment till I dont delete the Course Enrollment.

**Comment by RitvikSardana** [comment]
<img width="1440" alt="Screenshot 2024-02-21 at 10 58 05 AM" src="https://github.com/frappe/education/assets/65544983/21816284-470a-4cbc-9744-5f8ba672f35a">

So if you see here, you will notice that in version 15 you get this option where it automatically cancels.

**Comment by RitvikSardana** [comment]
Fixed: https://github.com/frappe/education/pull/178
