### ISSUE TITLE
Provision for Mark list

### ISSUE THREAD

**Issue by nitin-anantpranali** [frappe/education#206]
There should be provision for Mark Lists

**Comment by RitvikSardana** [comment]
Can you explain more @nitin-anantpranali ?

**Comment by nitin-anantpranali** [comment]
Rough Idea is
Based a student group, a list of students will be populated

and from there u can create a report card for each student
which will be stored in a new Doctype called maybe

“Report Card” or maybe something like that

which will be a combination of the exam conducted for that student group

and from there we can use Print Format to design a format for the report card

**Comment by RitvikSardana** [comment]
Duplicate Issue: https://github.com/frappe/education/issues/193
