### ISSUE TITLE
Module Profile not working correctly On ERPNext 15 with Education App

### ISSUE THREAD

**Issue by devatassimilate** [frappe/education#211]
We have setup ERPNext 15 version-15 branch and Education app with develop branch.
In this configuration, module profile not working correctly. Even module is unselected, it still getting shown on Workspace and Navbar options. 
Same is working on other site with different apps.

**Comment by RitvikSardana** [comment]
@devatassimilate 
can you share some ss?

**Comment by devatassimilate** [comment]
@RitvikSardana 

User's Module Profile
![image](https://github.com/frappe/education/assets/114396084/d3846a83-afdb-4dbf-ab70-05159f6ba827)
![image](https://github.com/frappe/education/assets/114396084/d38cd976-0822-4ab7-98eb-69eecb1557e9)

User's Desk Sidebar

![image](https://github.com/frappe/education/assets/114396084/23e02185-19e2-486a-b9bf-bd4f8d337d2c)

I am trying to figure out why it could happen but no success.

**Comment by devatassimilate** [comment]
@RitvikSardana Did you get chance to check this?

**Comment by RitvikSardana** [comment]
This is not replicable on my end @devatassimilate

**Comment by RitvikSardana** [comment]
@devatassimilate , is it still replicable on your end?

**Comment by maheshndev** [comment]
![image](https://github.com/frappe/education/assets/86865338/37f0824c-330c-4efc-ada5-f06e02f9be82)
Upon deactivating "Workspace Manager" This issue has been resolved. We can disable Workspace Manager in the Role Profile menu, and the menu will display the desired options. For example, we can choose to just see the Account Module.

Like This
![image](https://github.com/frappe/education/assets/86865338/4ea83255-144d-4b36-a25c-2b21a12c579e)
Thank You For Your Response @RitvikSardana
