### ISSUE TITLE
Customization issue in the student applicant form

### ISSUE THREAD

**Issue by Kirannegi02** [frappe/education#213]
1. In student applicant, we do not want the first_name, last_name, and middle_name
2. We have removed it from the Build > DocType > Student Applicant
3. We have updated the Website > Web Form > Student Applicant for the same
From the website, when I submit the form I get the following error on the console

09:35:36 web.1      | Traceback (most recent call last):
09:35:36 web.1      |   File "apps/frappe/frappe/app.py", line 106, in application
09:35:36 web.1      |     frappe.handler.handle()
09:35:36 web.1      |   File "apps/frappe/frappe/handler.py", line 49, in handle
09:35:36 web.1      |     data = execute_cmd(cmd)
09:35:36 web.1      |            ^^^^^^^^^^^^^^^^
09:35:36 web.1      |   File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
09:35:36 web.1      |     return frappe.call(method, **frappe.form_dict)
09:35:36 web.1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
09:35:36 web.1      |   File "apps/frappe/frappe/__init__.py", line 1697, in call
09:35:36 web.1      |     return fn(*args, **newargs)
09:35:36 web.1      |            ^^^^^^^^^^^^^^^^^^^^
09:35:36 web.1      |   File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
09:35:36 web.1      |     return func(*args, **kwargs)
09:35:36 web.1      |            ^^^^^^^^^^^^^^^^^^^^^
09:35:36 web.1      |   File "apps/frappe/frappe/rate_limiter.py", line 152, in wrapper
09:35:36 web.1      |     return fn(*args, **kwargs)
09:35:36 web.1      |            ^^^^^^^^^^^^^^^^^^^
09:35:36 web.1      |   File "apps/frappe/frappe/website/doctype/web_form/web_form.py", line 488, in accept
09:35:36 web.1      |     doc.insert(ignore_permissions=True, ignore_mandatory=ignore_mandatory)
09:35:36 web.1      |   File "apps/frappe/frappe/model/document.py", line 285, in insert
09:35:36 web.1      |     self.run_before_save_methods()
09:35:36 web.1      |   File "apps/frappe/frappe/model/document.py", line 1084, in run_before_save_methods
09:35:36 web.1      |     self.run_method("validate")
09:35:36 web.1      |   File "apps/frappe/frappe/model/document.py", line 955, in run_method
09:35:36 web.1      |     out = Document.hook(fn)(self, *args, **kwargs)
09:35:36 web.1      |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
09:35:36 web.1      |   File "apps/frappe/frappe/model/document.py", line 1315, in composer
09:35:36 web.1      |     return composed(self, method, *args, **kwargs)
09:35:36 web.1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
09:35:36 web.1      |   File "apps/frappe/frappe/model/document.py", line 1297, in runner
09:35:36 web.1      |     add_to_return_value(self, fn(self, *args, **kwargs))
09:35:36 web.1      |                               ^^^^^^^^^^^^^^^^^^^^^^^^^
09:35:36 web.1      |   File "apps/frappe/frappe/model/document.py", line 952, in fn
09:35:36 web.1      |     return method_object(*args, **kwargs)
09:35:36 web.1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
09:35:36 web.1      |   File "apps/education/education/education/doctype/student_applicant/student_applicant.py", line 33, in validate
09:35:36 web.1      |     self.set_title()
09:35:36 web.1      |   File "apps/education/education/education/doctype/student_applicant/student_applicant.py", line 42, in set_title
09:35:36 web.1      |     filter(None, [self.first_name, self.middle_name, self.last_name])
09:35:36 web.1      |                   ^^^^^^^^^^^^^^^
09:35:36 web.1      | AttributeError: 'StudentApplicant' object has no attribute 'first_name'
09:35:36 web.1      |

**Comment by RitvikSardana** [comment]
Yes so if you will remove first_name, then you will need to change accordingly in the whole codebase
