### ISSUE TITLE
On Install - Error

### ISSUE THREAD

**Issue by msalim79** [frappe/education#214]
Hi Ritvik
tried to install-app got the following error

![image](https://github.com/frappe/education/assets/30749464/44816478-a47c-493b-8799-285e8bf98f9b)

**Comment by msalim79** [comment]
Ive managed to fix this , and get the app going.

**Comment by ptpratul2** [comment]
> Ive managed to fix this , and get the app going.

How did you fix it? please explain, getting same error.
