### ISSUE TITLE
Education Settings - 'Student Naming By' [New Feature]

### ISSUE THREAD

**Issue by msalim79** [frappe/education#215]
Student Records Created by  Full Name and or Name Series
The relevant info should show on the GL and SOA.

**Example Below:**
![image](https://github.com/frappe/education/assets/30749464/d029a08b-bf3d-4b9a-9684-ca14eba8546b)

**Example:**
![image](https://github.com/frappe/education/assets/30749464/d147e55f-345d-4d8b-a5c1-37af0737ea25)

**Ledgers:**
![image](https://github.com/frappe/education/assets/30749464/cf6f976b-143c-411e-a8bf-7a40ad1fb911)

**Print Report:**
![image](https://github.com/frappe/education/assets/30749464/179431f1-852c-48d9-983d-dc771630c46e)

**Comment by msalim79** [comment]
Noted that a new customer gets created when creating a new student , the ledger links are still attached to "student" and not "customer" on the student master , this could be confusing to the end user.
Naming Series on the 'student' default to a number series whereas the 'customer' defaults to Full Name.

![image](https://github.com/frappe/education/assets/30749464/2cc56e59-dc37-41ee-b327-94f610d92214)

![image](https://github.com/frappe/education/assets/30749464/da3ac0c4-84cf-4c18-aeea-1e2d755dc5bb)

![image](https://github.com/frappe/education/assets/30749464/e243174b-437d-4d15-a97b-6e0075b1f13e)

**Comment by RitvikSardana** [comment]
Interesting, will look into it 👍

**Comment by ankush** [comment]
That feature in ERPNext is useless and from bygone era. 

If you want a naming series, you can just set it up from the "customise form" with ease.
