### ISSUE TITLE
Debit and Credit Not Equal for Payment Entry for Payments Entry against Education Fee Payment Received

### ISSUE THREAD

**Issue by Adan-Taimour** [frappe/education#22]
I created a Education Fee invoice for 1150/- .
While I make a Payment Received entry against it for 1150/-.
The payment entry gets saved but while I submit it it gives the following error

Debit and Credit not equal for Payment Entry #ACC-PAY-2022-00003. Difference is 2300.

Party Type Also do not show Student in List.

is there any solution.????

**Comment by chandrubiradar** [comment]
I also have same issue
Please fix this bug

**Comment by chandrubiradar** [comment]
@Adan-Taimour 
Are you able to find a work around?
If yes, please help me out
