### ISSUE TITLE
There was issue In Creating "Assessment Group"

### ISSUE THREAD

**Issue by maheshndev** [frappe/education#224]
### We Are Trying To Add Assessment Group But it Have A Problem To Create 
<img width="959" alt="image" src="https://github.com/frappe/education/assets/86865338/7f8c136d-2642-476f-9ee4-0a71220a44c6">

<img width="601" alt="image" src="https://github.com/frappe/education/assets/86865338/64fd07c2-9d3a-49a6-ac07-07accba71864">

![image](https://github.com/frappe/education/assets/86865338/95e30f25-7d2c-4d9a-ac63-2b5831757b3b)
**### Please Solve This As Soon As Posible**

**Comment by RitvikSardana** [comment]
Seems like some changes were made via DB in the assessment group, otherwise, whenever a tree doctype is created a root element is created automatically.

**Comment by RitvikSardana** [comment]
Can you tell me how  when did u first install Education?
are you of FC or local site?

**Comment by Nihantra-Patel** [comment]
Same Issue in Frapp Forum:

https://discuss.frappe.io/t/assessment-group-not-create/119438

https://discuss.frappe.io/t/i-am-facing-a-difficulty-while-creating-assessment-group/119440

**Comment by maheshndev** [comment]
> Can you tell me how when did u first install Education? are you of FC or local site?

it was in aws cloud and also same error occurred in Local

**Comment by RitvikSardana** [comment]
@maheshndev 

can you go to the DocType "Item Group" and let me know whether an entry for "Fee Component" is created or not?

like this: 
<img width="1211" alt="Screenshot 2024-03-21 at 2 29 40 PM" src="https://github.com/frappe/education/assets/65544983/92a62eb5-9d19-450e-92f8-572bb27e04db">

**Comment by maheshndev** [comment]
> @maheshndev
> 
> can you go to the DocType "Item Group" and let me know whether an entry for "Fee Component" is created or not?
> 
> like this: <img alt="Screenshot 2024-03-21 at 2 29 40 PM" width="1211" src="https://private-user-images.githubusercontent.com/65544983/315221196-92a62eb5-9d19-450e-92f8-572bb27e04db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMTM0MDMsIm5iZiI6MTcxMTAxMzEwMywicGF0aCI6Ii82NTU0NDk4My8zMTUyMjExOTYtOTJhNjJlYjUtOWQxOS00NTBlLTkyZjgtNTcyYmIyN2UwNGRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA5MjUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2N2ZhYmVkMWExZWZlZDRkMTA3OTVlNWVkMDllZThkNjZiYWJhYTViZTVhZTkzYWYyMzM4MjQyYTA1MDFhMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qFdMEkkKKAs1748Z6pMr_N-U1ZSG1BX-sl8vZITHO_4">

Thank You For Helping Me Its Get Solved

**Comment by RitvikSardana** [comment]
@maheshndev , how was it solved?
"All Assessment Groups" was created in "Assessment Group"?
