### ISSUE TITLE
Cannot enroll Student Applicant (Could not find Customer Group: Student & Value missing for Customer: Territory)

### ISSUE THREAD

**Issue by EkasaTech** [frappe/education#231]
I cannot enroll my Student Applicant. It says "Could not find Customer Group: Student"

My app version:
Education: v15.3.0
ERPNext: v14.66.2
Frappe Framework: v14.69.0

And here patch that installed
![patch education](https://github.com/frappe/education/assets/111553452/cacdfb48-ae5d-4371-b866-09875415841f)

**Comment by EkasaTech** [comment]
I try to add "Student" in my Customer_Group manually. but now it says "Error: Value missing for Customer: Territory"

**Comment by RitvikSardana** [comment]
Hii, were you able to solve this issue @EkasaTech ?

**Comment by EkasaTech** [comment]
I able to solve this manually by adding "Student" customer group.
But, why the update cannot add this automatically to my site?
i manage a few sites, and I need to add this "Student" document by myself?

For "Value missing for Customer:Territory" i can solve it by setup the default terittory on Selling Settings

**Comment by RitvikSardana** [comment]
Actually "Student" customer group is created while installing the app. 
I'm not quite sure why it wasn't created. Anyway I'll write a patch for it. You can just upgrade your site when the patch is merged.

**Comment by EkasaTech** [comment]
Yes, I'm aware about it.
I try to create a fresh site and when i install education app, everything is smooth.
Only if for existing site, the issue come up.

Ok Ritvik, thanks.
