### ISSUE TITLE
The default print format is not being used

### ISSUE THREAD

**Issue by saista2** [frappe/education#234]
I have set the default print for the fee in the sales invoice.
![image](https://github.com/frappe/education/assets/155412942/09223dbb-224d-41ae-8343-45f07d7368a6).
When I print it, it uses the sales invoice print format.
![image](https://github.com/frappe/education/assets/155412942/08577117-2862-4a00-9d20-2af180bb2f50)

**Comment by RitvikSardana** [comment]
Hey @saista2 , can you share the SS of the template?

**Comment by RitvikSardana** [comment]
fixed via: https://github.com/frappe/education/pull/235
