### ISSUE TITLE
error in enrolling student applicants

### ISSUE THREAD

**Issue by Tomkar9** [frappe/education#237]
![Screenshot (15)](https://github.com/frappe/education/assets/91272550/d8f24318-7ca7-4bde-92ba-3ae908efbe93)

this is the error i get when i try to enroll a student applicant after the person has fill the admission and has been approved

**Comment by RitvikSardana** [comment]
Duplicate issue #236

**Comment by Tomkar9** [comment]
Education: v15.0.0 (version-15)

ERPNext: v15.18.2 (version-15)

Frappe Framework: v15.19.0 (version-15)
