### ISSUE TITLE
Leave Status for Student Attendance

### ISSUE THREAD

**Issue by RitvikSardana** [frappe/education#241]
As of now for marking attendance of student, only 2 status are present.
1. Absent
2. Present

However "Leave" status can also be added in a case when student applies for leave.

**Comment by msalim79** [comment]
Absent With Leave 
Absent WithOut Leave(AWOL)

**Comment by RitvikSardana** [comment]
@msalim79 
<img width="1305" alt="Screenshot 2024-04-30 at 12 59 53 PM" src="https://github.com/frappe/education/assets/65544983/4c65229b-5c92-494d-ab90-06f7a96a9b3f">


Using the "Student Leave Application" DocType, both of the above status can be achieved.
