### ISSUE TITLE
Creating new Fees button missing

### ISSUE THREAD

**Issue by SaQDS** [frappe/education#246]
New Fees creation button is missing, have to create new one via accessing /app/fees/new  

![image](https://github.com/frappe/education/assets/28286890/45b45922-f659-487d-b432-a8f7b500203c)

Installed Apps
Agriculture: v0.0.1 (develop)
Frappe Builder: v1.x.x-develop () (develop)
Frappe CRM: v2.0.0-dev (develop)
Education: v15.3.0 (develop)
ERPNext: v15.20.6 (version-15)
Erpnext Telegram Integration: v1.2.0 (master)
Frappe Framework: v15.23.0 (version-15)
Frappe Whatsapp: v0.0.2 (master)
Frappe Health: v16.0.0-dev (develop)
Frappe LMS: v1.0.0 (develop)
Payments: v0.0.1 (develop)
Webshop: v0.0.1 (develop)
Wiki: v2.0.0 (master)

**Comment by SaQDS** [comment]
BTW, Student Portal seems not working well, some schedules are not show up for the courses if you update them into the program afterwards.

**Comment by Sudhegan** [comment]
i think these are moved to Doctype: fee category , that is why fees is read only

**Comment by SaQDS** [comment]
> i think these are moved to Doctype: fee category , that is why fees is read only

Not fee category, but Fee Schedule?

**Comment by RitvikSardana** [comment]
@SaQDS 
Fee doctype is for only old transactions, from v15.1 onwards Sales Invoice is created against a Fee Schedule.
From v15.3 onwards you have an option to create Sales Order Instead of Sales Invoice.

Docs: https://docs.frappe.io/education/fees


So the structure as of now is:

Fee Structure => Fee Schedule => Sales Invoice/ Sales Order

**Comment by RitvikSardana** [comment]
> BTW, Student Portal seems not working well, some schedules are not show up for the courses if you update them into the program afterwards.

can you share some SS of what is showing or what is not working?

**Comment by SaQDS** [comment]
> @SaQDS Fee doctype is for only old transactions, from v15.1 onwards Sales Invoice is created against a Fee Schedule. From v15.3 onwards you have an option to create Sales Order Instead of Sales Invoice.
> 
> Docs: https://docs.frappe.io/education/fees
> 
> So the structure as of now is:
> 
> Fee Structure => Fee Schedule => Sales Invoice/ Sales Order

Thanks A lot, now it's clear :)
