### ISSUE TITLE
student applicant not fetching student admission form name

### ISSUE THREAD

**Issue by Sudhegan** [frappe/education#248]
when a student is applying via admission in web site it doesn't fetch the student admission name in doctype: student applicant, it should be fetched automatically when applied via website

![image](https://github.com/frappe/education/assets/65366543/7c780fd8-302e-4bf2-bc4e-28d7885ad92d)

**Comment by RitvikSardana** [comment]
So for Admissions the procedure is

Student Applicant Webform takes Data and stores it into "Student Applicant" DocType which then you use to enroll the student or you can use Program Enrollment Tool to enroll student in BULK.

docs: https://docs.frappe.io/education/program-enrollment-tool
