### ISSUE TITLE
‘Student’ object has no attribute ‘set_missing_customer_details’

### ISSUE THREAD

**Issue by mansi31199** [frappe/education#254]
While creating Sales Invoice from Fee Schedule document system is giving below error:
‘Student’ object has no attribute ‘set_missing_customer_details’

**Comment by RitvikSardana** [comment]
@mansi31199 
Could you please add the steps to replicate the above behaviour?

Also mention the version of the education,ERPNext and frappe framework.

Share some screenshots

**Comment by mansi31199** [comment]
@RitvikSardana 
If a customer is not created for some students, and when we try to create a Sales Invoice from the Fee schedule, the system gives the error: 'Student' object has no attribute 'set_missing_customer_details'.

Education: v15.3.0
ERPNext: v15.23.0 (version-15)
Frappe Framework: v15.26.0 (version-15)

**Comment by RitvikSardana** [comment]
@mansi31199 

How was that student created?

**Comment by mansi31199** [comment]
@RitvikSardana 
Previously, I was using an older version of the Education app (v15.0.0), which did not create a customer upon the creation of a student. This caused the following error:
'Student' object has no attribute 'set_missing_customer_details.'
There is no function called set_missing_customer_details in the student object.
