### ISSUE TITLE
not merge in version-15 branch

### ISSUE THREAD

**Issue by mohsinalimat** [frappe/education#257]
Why below releases not merged in version-15 branch?

https://github.com/frappe/education/releases/tag/v15.3.0
https://github.com/frappe/education/releases/tag/v15.3.1

**Comment by RitvikSardana** [comment]
As mentioned before, other people are using the older version of education module which is on version 15, and don't want the new updates.

**Comment by mohsinalimat** [comment]
Then other users have new functionality. Then what can you do!

**Comment by RitvikSardana** [comment]
New users should use developer branch right?

**Comment by mohsinalimat** [comment]
No.

**Comment by mohsinalimat** [comment]
If version 16 released then your develop branch also version 16. If users have to stay in version 15 then what can you do?

**Comment by mohsinalimat** [comment]
> If version 16 released then your develop branch also version 16. If users have to stay in version 15 then what can you do?

??
