### ISSUE TITLE
Remove certain fee categories from the fee schedule when creating a fee schedule from the monthly fee structure

### ISSUE THREAD

**Issue by mansi31199** [frappe/education#261]
How can I remove certain fee categories from the fee schedule when creating a fee schedule from the monthly fee structure?

For example, some fees are charged once a year and others are only charged in specific months. For instance, ID card fees are charged yearly, and catering charges are only applied when the school is in session, such as for 9 or 10 months.

Currently, there is no option to delete fee components in the fee schedule, as the table is read-only. How can I work around this limitation to manage fees that are charged annually or only in specific months?

**Comment by RitvikSardana** [comment]
I am aware of the Feature Request,  this will be added in a few weeks.

The solution would be to select Fee Components which you will take over an year. While creating Fee Schedule, you can  define in which fee schedule you want to take which component.

**Comment by RitvikSardana** [comment]
added with #272
