### ISSUE TITLE
Field not permitted in query: fee_schedule

### ISSUE THREAD

**Issue by amet123** [frappe/education#270]
HI 

Error show only Education Dashboard 
![image](https://github.com/frappe/education/assets/326649/07d32f24-6551-4d5c-8387-b4c7d97cde2d)

Even when i try to create a Fee Schedule

[Error Click here ](https://discuss.frappe.io/t/during-eduction-module-when-create-fee-schedule/127072)

**Comment by RitvikSardana** [comment]
@amet123  please migrate your site using 
bench --site site-name migrate

**Comment by Zyten** [comment]
Can confirm this occurs for a fresh installation of Education app. `bench migrate` did not resolve the issue 

Frappe v15.31.0
Education v15.3.2

**Comment by amet123** [comment]
@RitvikSardana @Zyten  
fresh installation , even i try migrate command but still same issue

**Comment by RitvikSardana** [comment]
@Zyten @amet123 

have you guys installed ERPNext?

**Comment by amet123** [comment]
@RitvikSardana yes 

[Error Click here ](https://discuss.frappe.io/t/during-eduction-module-when-create-fee-schedule/127072)

**Comment by fbcudaipur** [comment]
I can confirm. This happens on a fresh install, even after running the migrate command.

**Comment by RitvikSardana** [comment]
Unable to replicate it locally.

**Comment by johnwslongland** [comment]
Why has this issue been closed ?

I am getting the same. Fresh install of erpnext ( V15). As suggested above I did a bench migrate ( bench restart). Problem persists. I have opened many of the doctypes and they all seem to open but everytime I click on education-module or I use the browser back-button to go back to the education-root, the same message pops up.

I see in my error-log there is an erorr : Exception during  setup ..

Traceback with variables (most recent call last):
  File "apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 423, in make_records
    doc.insert(ignore_permissions=True, ignore_if_duplicate=True)
      records = [{'doctype': 'Party Type', 'party_type': 'Student', 'account_type': 'Receivable'}, {'doctype': 'Item Group', 'item_group_name': 'Fee Component'}, {'doctype': 'Customer Group', 'customer_group_name': 'Student'}]
      debug = False
      _dict = <class 'frappe._dict'>
      scrub = <function scrub at 0xffffa78fc540>
      record = {'doctype': 'Party Type', 'party_type': 'Student', 'account_type': 'Receivable'}
      doctype = 'Party Type'
      condition = None
      doc = <PartyType: unsaved>
      parent_link_field = 'parent_party_type'
      savepoint = 'setup_fixtures_creation'
      e = LinkValidationError('Could not find Party Type: Student')
      exception = None
  File "apps/frappe/frappe/model/document.py", line 283, in insert
    self._validate_links()
      self = <PartyType: unsaved>
      ignore_permissions = True
      ignore_links = None
      ignore_if_duplicate = True
      ignore_mandatory = None
      set_name = None
      set_child_names = True
  File "apps/frappe/frappe/model/document.py", line 930, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg), frappe.LinkValidationError)
      self = <PartyType: unsaved>
      invalid_links = [('party_type', 'Student', 'Party Type: Student')]
      cancelled_links = []
      msg = 'Party Type: Student'
  File "apps/frappe/frappe/__init__.py", line 645, in throw
    msgprint(
      msg = 'Could not find Party Type: Student'
      exc = <class 'frappe.exceptions.LinkValidationError'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 610, in msgprint
    _raise_exception()
      msg = 'Could not find Party Type: Student'
      title = None
      raise_exception = <class 'frappe.exceptions.LinkValidationError'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0xffffa3e9f6a0>
      inspect = <module 'inspect' from '/usr/lib/python3.12/inspect.py'>
      out = {'message': 'Could not find Party Type: Student', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'b6c52c55c34ccc01ffa3523d4ef59752655020de66ce7b3fc9e12af5'}
  File "apps/frappe/frappe/__init__.py", line 561, in _raise_exception
    raise exc
      exc = LinkValidationError('Could not find Party Type: Student')
      inspect = <module 'inspect' from '/usr/lib/python3.12/inspect.py'>
      msg = 'Could not find Party Type: Student'
      out = {'message': 'Could not find Party Type: Student', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'b6c52c55c34ccc01ffa3523d4ef59752655020de66ce7b3fc9e12af5'}
      raise_exception = <class 'frappe.exceptions.LinkValidationError'>
frappe.exceptions.LinkValidationError: Could not find Party Type: Student

**Comment by RitvikSardana** [comment]
This issue was closed due to inactivity.

Last reply was 25 days ago.

Send me the apps and versions which you have installed

**Comment by saadimam01** [comment]
Hello anyone available?

Is there any update on this cause.

**Comment by johnwslongland** [comment]
Here is what I did to get rid of the error..

ERPNExt already installed
bench get-app education
bench update --reset
bench --site migrate
bench restart
bench --site install-app education
bench --site migrate
bench restart

bench get-app lms
bench update --reset
bench --site migrate
bench restart
bench --site install-app lms
bench --site migrate
bench restart


Edit : Perhaps it looks like an over-kill , but it worked

**Comment by saadimam01** [comment]
I have tried all this but in lms it always stuck due to the following issue;

(!) Some chunks are larger than 500 KiB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/guide/en/#outputmanualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.


Is there any valid solution for this in-order to finish there setup.?

**Comment by saadimam01** [comment]
Is there any update please?

**Comment by saadimam01** [comment]
### App Versions
```
{
	"education": "15.5.0",
	"erpnext": "15.33.5",
	"frappe": "15.39.0",
	"hrms": "16.0.0-dev",
	"non_profit": "0.0.1",
	"payments": "0.0.1",
	"webshop": "0.0.1",
	"zatca_erpgulf": "0.0.1"
}
```
### Route
```
Form/Fee Schedule/new-fee-schedule-potbecbjya
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1768, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 42, in savedocs
    run_onload(doc)
  File "apps/frappe/frappe/desk/form/load.py", line 351, in run_onload
    doc.run_method("onload")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/education/education/education/doctype/fee_schedule/fee_schedule.py", line 17, in onload
    info = self.get_dashboard_info()
  File "apps/education/education/education/doctype/fee_schedule/fee_schedule.py", line 46, in get_dashboard_info
    fees_amount = frappe.db.sql(
  File "apps/frappe/frappe/database/database.py", line 234, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'fee_schedule' in 'where clause'")

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"owner\":\"Administrator\",\"docstatus\":0,\"idx\":0,\"fee_structure\":\"EDU-FST-2024-00001\",\"posting_date\":\"2024-08-24\",\"naming_series\":\"EDU-FSH-.YYYY.-\",\"send_email\":0,\"program\":\"Bachelor's in Computer Science\",\"academic_year\":\"2018-19\",\"currency\":\"SAR\",\"total_amount\":75000,\"grand_total\":0,\"letter_head\":\"Yousif\",\"receivable_account\":\"1310 - مدينون - I\",\"company\":\"Imdady\",\"cost_center\":\"رئيسي - I\",\"status\":\"Draft\",\"doctype\":\"Fee Schedule\",\"student_groups\":[{\"docstatus\":0,\"doctype\":\"Fee Schedule Student Group\",\"name\":\"new-fee-schedule-student-group-vedxpkwsav\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"parent\":\"new-fee-schedule-potbecbjya\",\"parentfield\":\"student_groups\",\"parenttype\":\"Fee Schedule\",\"idx\":1,\"__unedited\":false,\"student_group\":\"Section A\"}],\"components\":[{\"owner\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"fees_category\":\"Fall\",\"amount\":75000,\"item\":\"Fall\",\"discount\":0,\"total\":75000,\"parentfield\":\"components\",\"parenttype\":\"Fee Schedule\",\"doctype\":\"Fee Component\",\"__islocal\":1,\"__unsaved\":1,\"parent\":\"new-fee-schedule-potbecbjya\",\"name\":\"new-fee-component-zgomhjvruu\"}],\"__islocal\":1,\"__onload\":{\"load_after_mapping\":true},\"__unsaved\":1,\"name\":\"new-fee-schedule-potbecbjya\",\"__last_sync_on\":\"2024-08-24T06:58:29.353Z\",\"due_date\":\"2024-09-30\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery370058710651952061581": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 1821,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "pymysql.err.OperationalError: (1054, \"Unknown column 'fee_schedule' in 'where clause'\")",
	"exc_type": "OperationalError",
	"_exc_source": "education (app)"
}
```

**Comment by RitvikSardana** [comment]
This repo is for frappe Education , please go to frappe LMS to report the issue @saadimam01

**Comment by saadimam01** [comment]
@RitvikSardana Brother, I'm getting the error in education actually while adding the fee Schedule not in LMS

**Comment by RitvikSardana** [comment]
Can you try installing a new site, with only ERPNext and Education and let me know whether you still get the same issue or not?

**Comment by saadimam01** [comment]
Hello @RitvikSardana This works to me on another site (Y)

**Comment by saadimam01** [comment]
Hello Team,

I'm trying to create a new doctype in version 15 and it is not getting the total amount, when I'm using Fee Component as a table in my new Doctype:

![FEE](https://github.com/user-attachments/assets/c8e9445c-778e-4835-a899-6f5466e38c98)

**Comment by msalim79** [comment]
this here is still an issue after running bench migrate and bench restart , this is a new install of erpnext and education.
