### ISSUE TITLE
Incorrect Date Generation in Quarterly Fee Schedule

### ISSUE THREAD

**Issue by mansi31199** [frappe/education#271]
When setting up a fee schedule for a Quarterly fee plan, with Academic year start date as 01-04-2024 and year end date as 31-03-2025, the system is generating dates incorrectly. Instead of the expected schedule of 01-04-2024, 01-07-2024, 01-10-2024, 01-01-2025, it is generating 01-04-2024, 01-07-2024, 01-10-2024, 01-01-2024.

Steps to Reproduce:

Set Academic year start date to 01-04-2024 and year end date to 31-03-2025.
Create a fee schedule for a Quarterly fee plan.
Observe the generated dates.
Expected Behavior:
The generated dates should follow the academic year, ending with 01-01-2025 for Quarterly fee plan.

Actual Behaviour:
The generated dates end with 01-01-2024 instead of 01-01-2025.

![image](https://github.com/frappe/education/assets/101191473/e0d13782-5d04-4b18-9821-f5a6d3c70025)

**Comment by RitvikSardana** [comment]
fixed with #272
