### ISSUE TITLE
Installing error

### ISSUE THREAD

**Issue by yahyaoudra** [frappe/education#273]
during installation

Document Insert Error
Traceback (most recent call last):
  File "apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 423, in make_records
    doc.insert(ignore_permissions=True, ignore_if_duplicate=True)
  File "apps/frappe/frappe/model/document.py", line 283, in insert
    self._validate_links()
  File "apps/frappe/frappe/model/document.py", line 930, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg), frappe.LinkValidationError)
  File "apps/frappe/frappe/__init__.py", line 645, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 610, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 561, in _raise_exception
    raise exc
frappe.exceptions.LinkValidationError: Could not find Party Type: Student

An error occurred while installing education: Module import failed for Assessment Group, the DocType you're trying to open might be deleted.<br> Error: No module named 'frappe.core.doctype.assessment_group'
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 445, in install_app
    _install_app(app, verbose=context.verbose, force=force)
      context = {'sites': ['portal.softskills.ma'], 'force': False, 'verbose': False, 'profile': False}
      apps = ('education',)
      force = False
      _install_app = <function install_app at 0x7f1909980860>
      filelock = <function filelock at 0x7f1909975c60>
      exit_code = 0
      site = 'portal.softskills.ma'
      app = 'education'
      err = ImportError("Module import failed for Assessment Group, the DocType you're trying to open might be deleted.<br> Error: No module named 'frappe.core.doctype.assessment_group'")
  File "apps/frappe/frappe/installer.py", line 311, in install_app
    frappe.get_attr(after_install)()
      name = 'education'
      verbose = False
      set_as_patched = True
      force = False
      sync_jobs = <function sync_jobs at 0x7f1908789260>
      sync_for = <function sync_for at 0x7f190878a0c0>
      sync_customizations = <function sync_customizations at 0x7f190991a2a0>
      sync_fixtures = <function sync_fixtures at 0x7f190878a3e0>
      app_hooks = {'accounting_dimension_doctypes': ['Fee Schedule', 'Fee Structure'], 'after_install': ['education.install.after_install'], 'app_color': ['grey'], 'app_description': ['Education'], 'app_email': ['hello@frappe.io'], 'app_icon': ['octicon octicon-file-directory'], 'app_include_js': ['education.bundle.js'], 'app_license': ['GNU GPL V3'], 'app_name': ['education'], 'app_publisher': ['Frappe Technologies Pvt. Ltd.'], 'app_title': ['Education'], 'app_version': ['15.3.2'], 'before_tests': ['education.education.test_utils.before_tests'], 'calendars': ['Course Schedule'], 'default_roles': [{'role': 'Student', 'doctype': 'Student', 'email_field': 'student_email_id'}], 'domains': {'Education': ['education.education.setup']}, 'global_search_doctypes': {'Education': [{'doctype': 'Article', 'index': 1}, {'doctype': 'Video', 'index': 2}, {'doctype': 'Topic', 'index': 3}, {'doctype': 'Course', 'index': 4}, {'doctype': 'Program', 'index': 5}, {'doctype': 'Quiz', 'index': 6}, {'doctype': 'Question', 'ind...
      installed_apps = ['frappe', 'erpnext']
      app = 'erpnext'
      required_app = 'erpnext'
      after_install = 'education.install.after_install'
  File "apps/education/education/install.py", line 10, in after_install
    create_parent_assessment_group()
  File "apps/education/education/install.py", line 30, in create_parent_assessment_group
    frappe.get_doc(
  File "apps/frappe/frappe/__init__.py", line 1333, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
      args = ({'doctype': 'Assessment Group', 'assessment_group_name': 'All Assessment Groups', 'is_group': 1},)
      kwargs = {}
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
  File "apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
      args = ({'doctype': 'Assessment Group', 'assessment_group_name': 'All Assessment Groups', 'is_group': 1},)
      kwargs = {'doctype': 'Assessment Group', 'assessment_group_name': 'All Assessment Groups', 'is_group': 1}
      doctype = 'Assessment Group'
  File "apps/frappe/frappe/model/base_document.py", line 70, in get_controller
    site_controllers[doctype] = import_controller(doctype)
      doctype = 'Assessment Group'
      site_controllers = {'Module Def': <class 'frappe.core.doctype.module_def.module_def.ModuleDef'>, 'DocField': <class 'frappe.core.doctype.docfield.docfield.DocField'>, 'DocPerm': <class 'frappe.core.doctype.docperm.docperm.DocPerm'>, 'DocType Link': <class 'frappe.core.doctype.doctype_link.doctype_link.DocTypeLink'>, 'System Settings': <class 'frappe.core.doctype.system_settings.system_settings.SystemSettings'>, 'Notification Settings': <class 'frappe.desk.doctype.notification_settings.notification_settings.NotificationSettings'>, 'DefaultValue': <class 'frappe.core.doctype.defaultvalue.defaultvalue.DefaultValue'>, 'Payment Reconciliation': <class 'erpnext.accounts.doctype.payment_reconciliation.payment_reconciliation.PaymentReconciliation'>, 'Customize Form': <class 'frappe.custom.doctype.customize_form.customize_form.CustomizeForm'>, 'DocType Action': <class 'frappe.core.doctype.doctype_action.doctype_action.DocTypeAction'>, 'DocType State': <class 'frappe.core.doctype.doctype_state.doctype_state.DocTyp...
  File "apps/frappe/frappe/model/base_document.py", line 95, in import_controller
    module = load_doctype_module(doctype, module_name)
      doctype = 'Assessment Group'
      Document = <class 'frappe.model.document.Document'>
      NestedSet = <class 'frappe.utils.nestedset.NestedSet'>
      module_name = 'Core'
      doctype_info = None
      module_path = None
      class_overrides = {'Address': ['erpnext.accounts.custom.address.ERPNextAddress']}
  File "apps/frappe/frappe/modules/utils.py", line 254, in load_doctype_module
    raise ImportError(msg) from e
      doctype = 'Assessment Group'
      module = 'Core'
      prefix = ''
      suffix = ''
      app = 'frappe'
      key = ********
      module_name = 'frappe.core.doctype.assessment_group.assessment_group'
      msg = "Module import failed for Assessment Group, the DocType you're trying to open might be deleted.<br> Error: No module named 'frappe.core.doctype.assessment_group'"
builtins.ImportError: Module import failed for Assessment Group, the DocType you're trying to open might be deleted.<br> Error: No module named 'frappe.core.doctype.assessment_group'

**Comment by Sudhegan** [comment]
pls specify the install method, version of frappe and all other app installed together

**Comment by RitvikSardana** [comment]
@yahyaoudra 
please uninstall and re-install education
