### ISSUE TITLE
Domain Settings - ModuleNotFoundError: No module named 'education.education.setup'

### ISSUE THREAD

**Issue by Elkanaaa** [frappe/education#277]
Hi

When I select a domain and try to save I get: Server Error - ModuleNotFoundError: No module named 'education.education.setup'

Only retail & manufacturing domains appearing.

A fresh ERPNext install
+------------------------+---------+------------+---------+
| App                    | Version | Branch     | Commit  |
+------------------------+---------+------------+---------+
| ecommerce_integrations | 1.20.1  | main       | c12600d |
| education              | 15.0.0  | version-15 | ce33800 |
| erpnext                | 15.29.3 | version-15 | f975333 |
| frappe                 | 15.34.0 | version-15 | 9194eaf |
| hrms                   | 15.23.1 | version-15 | aa9f44c |
| it_management          | 0.0.1   | version-15 | 1ef1683 |
| payments               | 0.0.1   | version-15 | a3a84cd |
+------------------------+---------+------------+---------+

Seems others have had this: [https://github.com/frappe/erpnext/issues/39504](url)
And: [https://github.com/frappe/education/issues/102](url)

**Comment by RitvikSardana** [comment]
Education is a separate app now install it using

bench get-app education

**Comment by Elkanaaa** [comment]
OK - so it is supposed to be installed in its own right as a Frappe app that doesn't need ERPNext - like the Changemakers app?

If that's the case then problems with setting up multi-tenancy on local server not using FQDNs.

**Comment by Sudhegan** [comment]
it does need erpnext
