### ISSUE TITLE
Duplicate Topics getting added on Course Topic child table on Course Doctype

### ISSUE THREAD

**Issue by PratikM34** [frappe/education#35]
**Description of the issue**
Duplicate Topics getting added on Course Topic child table on Course Doctype
Domain : Education
Doctype: Course
ChildTable : Course Topic

**Issue Screenshot**
![Course_doc](https://user-images.githubusercontent.com/55180738/74584087-4ebf5d00-4ff4-11ea-830c-c764a4840390.png)

**Steps to reproduce the issue**
1.Go to Course List
2.Create New Course
3. Click on add on Topic child table
4. You can add multiple Topics to the same Course.
5. Ideally there must be only one Topic to one course.

**Expected Result**
1. Child Table should display topics which are not in selected Topics

**Comment by pateljannat** [comment]
<img width="1440" alt="Screenshot 2022-12-12 at 4 36 05 PM" src="https://user-images.githubusercontent.com/31363128/207030068-d64a9df9-c6d0-407e-8d99-95f2c776290e.png">

@PratikM34 I am unable to replicate this issue on my site. Can you please update your site and verify if the issue still persists?

**Comment by RitvikSardana** [comment]
This issue is fixed
