### ISSUE TITLE
Future date of birth accepted in Student Application

### ISSUE THREAD

**Issue by anuradha-8** [frappe/education#41]
**Steps to reproduce the issue:**
1] Go to Student Application form
2] Create new Student Application
3] Enter future date on date of birth field

**Description:** 
Future date of birth accepted in Student Application

**Expected Result**:  
Throw error on save for date of birth cannot be a future date on Student Application

**Comment by pateljannat** [comment]
There is a validation now for this.

<img width="1104" alt="Screenshot 2022-12-01 at 5 16 46 PM" src="https://user-images.githubusercontent.com/31363128/205045414-637e14ef-036c-4939-8efd-096022130f89.png">
