### ISSUE TITLE
Page education-settings not found

### ISSUE THREAD

**Issue by chipohameja** [frappe/education#48]
Whenever I open a single doctype under the education module, I got `Page [single-doctype-name] not found`. For instance, when I open Education Settings, I get `Page education-settings not found`. I've tried migrating the site and running bench build but nothing has changed.

![image](https://user-images.githubusercontent.com/44099664/197846075-7dfb94af-caf5-472b-8d89-cc6426794e8f.png)

**Comment by Daniel-OS01** [comment]
@MahMaejah 
Solution:
https://github.com/frappe/erpnext/issues/32767#issuecomment-1300389619

**Comment by chipohameja** [comment]
Thanks a lot @dragon3252, it's now working.
