### ISSUE TITLE
Education Fees Not updating Correctly After - Disocunt allowed or Write Off

### ISSUE THREAD

**Issue by tjomtek** [frappe/education#59]
### Information about bug

Case Scenario:
Student (A) has total fees of 10000(example) and pays 2500(example) , the school gives a discount of 2000 , so in total the system sees it as a 4500 in payment in the student ledger , however on the fees doctype , the system only takes into account the paid amount of 2500 and shows total owing as 10000-2500=7500 but in the student ledger the total owing is 5500 after discount. The total owing or outstanding should be the same there should not be a mismatch between the ledger and what is on the actual fees doctype.

Actual Case:

On Fees Payment Doctype:

![PaymentEntryDoc](https://user-images.githubusercontent.com/77873407/188561896-d0a6bb64-bfb7-475b-b34d-39f35a71305c.png)

On Fees Payment Doctype:

![FeesOutstandingTable](https://user-images.githubusercontent.com/77873407/188561889-21ba3e98-2b17-448f-8751-e59a8d9b3826.png)

On Student Ledger: 

![StudentLedger](https://user-images.githubusercontent.com/77873407/188561900-f45cd542-ee08-49f2-a11b-75541a4162fe.png)

On payment Request :

![payment Request](https://user-images.githubusercontent.com/77873407/188563041-7f71d1ca-78a9-4176-84fa-31582693c225.png)

### Module

education

### Version

ERPNext: v13.7.0 (version-13)

Frappe Framework: v13.7.0 (version-13)

**Comment by pateljannat** [comment]
@tjomtek how did you add discount to the Fees?

**Comment by tjomtek** [comment]
Sorry for the late response:
So i added a new account to the COA as "discount allowed" under expenses same as write off.
Then when i processed the payment i added the new line "discount allowed" under the tab "deductions or losses" and processed.

**Comment by arvind-hasti** [comment]
Hi @tjomtek @pateljannat Any updates on this? I'm also facing the same issue. 

**Version**
ERPNext: v13.42.3
Frappe Framework: v13.45.3

**Comment by tjomtek** [comment]
nope ...

**Comment by arvind-hasti** [comment]
@tjomtek @pateljannat 
These steps worked for me (the outstanding amount reflects the paid amount + discounts). LMK if this solves yours!

To allocate discounts for students' fees, follow these steps:
- In the Fee record of the student
- Click on Create payment -> This takes you to the 'new payment entry' page.
- Here enter the paid amount as the actual paid amount by the student party.
- Now **change the allocated amount in the invoice row** (Reference section shows invoices) to reflect the total payment (paid + discount amount)
- This will update the total allocated amount.
- When the total allocated amount > paid amount, this automatically shows the difference amount along with a write-off button.
- Click on the "Write Off Difference Amount" button. This adds the difference amount as a row in the "Deductions or Loss" section.
- Save and submit the payment entry.
- Go back to the fee record and check the outstanding amount

**Comment by msalim79** [comment]
@arvind-hasti sorry for the very late response ...
Method does work , however the ledgers could do with some enhancements , to show actual payment less write\deduction.

**Comment by RitvikSardana** [comment]
@tjomtek 
Yes as of now, this method is the only way to give discounts on Fees.

@msalim79 
what do u mean by enhancements in the ledger, can you give me an example?

**Comment by RitvikSardana** [comment]
Irrelevent due to : https://github.com/frappe/education/pull/181
