### ISSUE TITLE
Bug+: Payment Entry no longer recognizes Fees docs

### ISSUE THREAD

**Issue by this-gavagai** [frappe/education#7]
On the latest ERPNext Beta (v14-beta5), the payment entry doctype no longer recognizes Students as a Party Type nor Fees as an Invoice. This was a deliberate change.

Going forward, how should we accept payment on Fees documents?

**Comment by this-gavagai** [comment]
Any plans for this @deepeshgarg007? I'm happy to contribute code as I can, but there are some structural decisions to be made here it would seem.

**Comment by this-gavagai** [comment]
Any thoughts on a solution here? I'm happy to put some work in, but I don't have any sense of what's planned or in the pipeline.

**Comment by naquiuddin** [comment]
Yeah, Looks like this still exist. I think the party type `student` for education and many other ones are missing.

### App Versions
```
{
	"education": "0.0.1",
	"erpnext": "14.0.0-beta.6",
	"frappe": "14.0.0-beta.5"
}
```
### Route
```
Form/Fees/EDU-FEE-2022-00057
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1574, in call
    return fn(*args, **newargs)
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 1780, in get_payment_entry
    party_type = set_party_type(dt)
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 1929, in set_party_type
    return party_type
UnboundLocalError: local variable 'party_type' referenced before assignment

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"dt": "Fees",
		"dn": "EDU-FEE-2022-00057"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/erpnext.accounts.doctype.payment_entry.payment_entry.get_payment_entry"
}
```
### Response Data
```
{
	"exception": "UnboundLocalError: local variable 'party_type' referenced before assignment"
}
```

**Comment by this-gavagai** [comment]
v14 is officially out, but sadly the education module seems to have been left behind. As mentioned, I'm happy to put some time towards this, but I don't want to act unilaterally if there's already a vision for how this bug and others should be dealt with.

Is something in the works, or should the community begin work too?

**Comment by ankush** [comment]
https://github.com/frappe/erpnext/pull/31830 
https://github.com/frappe/education/pull/12

These should should've fixed it now @this-gavagai

**Comment by this-gavagai** [comment]
Thanks @ankush. It's working to some extent now, but it's quite buggy. Just as an example, when I try to cancel payments made against fees docs, I now get an error `AttributeError: 'Fees' object has no attribute 'base_grand_total'`. I'll try to dig in to figure out what's going on.

**Comment by this-gavagai** [comment]
I'm not able to reproduce the 'base_grand_total' bug consistently yet, but it's come up multiple times in my tests.

Another issue: payments by students are no longer appearing in the payment reconciliation tool, possibly due to the hard-coded string ninjutsu going on here:
https://github.com/frappe/erpnext/blob/6881b68ed7a97cdfb13af5d2d04739c2a7e16df3/erpnext/controllers/accounts_controller.py#L2094

I commend you guys for trying to decouple the payment entry doctype from specific voucher doctypes, but there's an enormous tech debt still to be paid. In the meantime, I think it's accurate to say that the education module is not working in v14 yet. I really wish that were posted somewhere.

**Comment by RitvikSardana** [comment]
Hey @this-gavagai 

are you still facing the issue?

**Comment by RitvikSardana** [comment]
It works as expected in V15,

Closing the issue due to inactivity, re-open if you still face the problem @this-gavagai
