### ISSUE TITLE
Numerical values for age field shows up in calendar mode in YYYY-MM-DD format in Education (Schools)

### ISSUE THREAD

**Issue by zenny** [frappe/education#73]
Redireted from https://discuss.erpnext.com/t/school-module-some-odds/31901/2?u=zenny.

Minimum and Maximum Age for the Admission doctype are only available in the calendar values in YYYY-MM-DD, not in number of age in YY.

Thanks!

**Comment by pateljannat** [comment]
<img width="1409" alt="Screenshot 2022-12-09 at 11 52 02 AM" src="https://user-images.githubusercontent.com/31363128/206638102-4bf10203-7f74-400e-be14-1984fd254a67.png">

Age for admission is now accepted in numbers and not calendar values.
