### ISSUE TITLE
No self hosted video on the erpnext server

### ISSUE THREAD

**Issue by christulsi** [frappe/education#9]
The LMS system is limited to video from vimeo and youtube, Can it not support self hosted videos on the server?

**Comment by ankush** [comment]
It probably can, since the video player supports direct media links... this is more of a Framework feature though. 

reference: https://github.com/sampotts/plyr#the-source-setter 


Keep in mind that Frappe Framework's file serving is not designed for streaming like this AFAIK.

**Comment by pateljannat** [comment]
@christulsi have you tried the [Frappe LMS App](https://github.com/frappe/lms)

**Comment by christulsi** [comment]
@pateljannat, I have used an earlier build and  got to upload a video via file upload and got it to play but using the video function using the link but the method was too complicated for an regular end user

**Comment by pateljannat** [comment]
@christulsi 
The app has undergone changes since then. You should have a look
