### ISSUE TITLE
Branching education app

### ISSUE THREAD

**Issue by rtdany10** [frappe/education#93]
Since a lot of users use the education app, it is always a good idea to branch out a stable version rather than keeping just the develop branch. Breaking changes affects users in production, breaks their workflows. 

It is a humble request to at least have a `version-14 ` branch so that breaking changes on develop doesn't directly affect end users.

**Comment by asifmohtesham** [comment]
@rtdany10 Did you get this to work on `version-14`?

**Comment by RitvikSardana** [comment]
v15.0.0 is out now
all the new feature which I will work on will be on the develop branch
