### ISSUE TITLE
Error while adding sibling details in student

### ISSUE THREAD

**Issue by reeta-greycube** [frappe/education#95]
1.While adding a sibling in a student we got this error :- 

![image](https://user-images.githubusercontent.com/110815754/213970489-89cf2dc1-cb35-476d-bfd4-430ccb2f7c2e.png)

**Comment by vr-greycube** [comment]
title cannot be used in add_fetch.
student_name is fetched from title with add_fetch. which causes this error
https://github.com/frappe/education/blob/eb3b5a39486d9d5ab39eed57f9b68d74baf591ba/education/education/doctype/student/student.js#L7
